/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMistakesRouteImport } from './routes/_authenticated/mistakes'
import { Route as AuthenticatedLearningRouteImport } from './routes/_authenticated/learning'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedBattleRouteImport } from './routes/_authenticated/battle'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCommunityIndexRouteImport } from './routes/_authenticated/community.index'
import { Route as AuthenticatedBattleIndexRouteImport } from './routes/_authenticated/battle.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedResultsSessionIdRouteImport } from './routes/_authenticated/results.$sessionId'
import { Route as AuthenticatedQuizSessionIdRouteImport } from './routes/_authenticated/quiz.$sessionId'
import { Route as AuthenticatedProfileUserIdRouteImport } from './routes/_authenticated/profile.$userId'
import { Route as AuthenticatedCommunityGroupsRouteImport } from './routes/_authenticated/community.groups'
import { Route as AuthenticatedCommunityFeedRouteImport } from './routes/_authenticated/community.feed'
import { Route as AuthenticatedCommunityDoubtsRouteImport } from './routes/_authenticated/community.doubts'
import { Route as AuthenticatedBattleWalletRouteImport } from './routes/_authenticated/battle.wallet'
import { Route as AuthenticatedBattleMegaRouteImport } from './routes/_authenticated/battle.mega'
import { Route as AuthenticatedBattleLeaderboardRouteImport } from './routes/_authenticated/battle.leaderboard'
import { Route as AuthenticatedBattleHistoryRouteImport } from './routes/_authenticated/battle.history'
import { Route as AuthenticatedAdminWithdrawalsRouteImport } from './routes/_authenticated/admin.withdrawals'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin.moderation'
import { Route as ApiPublicHooksRazorpayRouteImport } from './routes/api/public/hooks/razorpay'
import { Route as ApiPublicHooksProcessWithdrawalsRouteImport } from './routes/api/public/hooks/process-withdrawals'
import { Route as ApiPublicHooksMegaTestLifecycleRouteImport } from './routes/api/public/hooks/mega-test-lifecycle'
import { Route as AuthenticatedCommunityPostPostIdRouteImport } from './routes/_authenticated/community.post.$postId'
import { Route as AuthenticatedCommunityGroupGroupIdRouteImport } from './routes/_authenticated/community.group.$groupId'
import { Route as AuthenticatedCommunityForumCategoryIdRouteImport } from './routes/_authenticated/community.forum.$categoryId'
import { Route as AuthenticatedCommunityDoubtDoubtIdRouteImport } from './routes/_authenticated/community.doubt.$doubtId'
import { Route as AuthenticatedBattlePlaySessionIdRouteImport } from './routes/_authenticated/battle.play.$sessionId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMistakesRoute = AuthenticatedMistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearningRoute = AuthenticatedLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBattleRoute = AuthenticatedBattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityIndexRoute =
  AuthenticatedCommunityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedBattleIndexRoute =
  AuthenticatedBattleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBattleRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedResultsSessionIdRoute =
  AuthenticatedResultsSessionIdRouteImport.update({
    id: '/results/$sessionId',
    path: '/results/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuizSessionIdRoute =
  AuthenticatedQuizSessionIdRouteImport.update({
    id: '/quiz/$sessionId',
    path: '/quiz/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileUserIdRoute =
  AuthenticatedProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunityGroupsRoute =
  AuthenticatedCommunityGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCommunityFeedRoute =
  AuthenticatedCommunityFeedRouteImport.update({
    id: '/feed',
    path: '/feed',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCommunityDoubtsRoute =
  AuthenticatedCommunityDoubtsRouteImport.update({
    id: '/doubts',
    path: '/doubts',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedBattleWalletRoute =
  AuthenticatedBattleWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedBattleRoute,
  } as any)
const AuthenticatedBattleMegaRoute = AuthenticatedBattleMegaRouteImport.update({
  id: '/mega',
  path: '/mega',
  getParentRoute: () => AuthenticatedBattleRoute,
} as any)
const AuthenticatedBattleLeaderboardRoute =
  AuthenticatedBattleLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedBattleRoute,
  } as any)
const AuthenticatedBattleHistoryRoute =
  AuthenticatedBattleHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedBattleRoute,
  } as any)
const AuthenticatedAdminWithdrawalsRoute =
  AuthenticatedAdminWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksRazorpayRoute = ApiPublicHooksRazorpayRouteImport.update({
  id: '/api/public/hooks/razorpay',
  path: '/api/public/hooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessWithdrawalsRoute =
  ApiPublicHooksProcessWithdrawalsRouteImport.update({
    id: '/api/public/hooks/process-withdrawals',
    path: '/api/public/hooks/process-withdrawals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMegaTestLifecycleRoute =
  ApiPublicHooksMegaTestLifecycleRouteImport.update({
    id: '/api/public/hooks/mega-test-lifecycle',
    path: '/api/public/hooks/mega-test-lifecycle',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCommunityPostPostIdRoute =
  AuthenticatedCommunityPostPostIdRouteImport.update({
    id: '/post/$postId',
    path: '/post/$postId',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCommunityGroupGroupIdRoute =
  AuthenticatedCommunityGroupGroupIdRouteImport.update({
    id: '/group/$groupId',
    path: '/group/$groupId',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCommunityForumCategoryIdRoute =
  AuthenticatedCommunityForumCategoryIdRouteImport.update({
    id: '/forum/$categoryId',
    path: '/forum/$categoryId',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCommunityDoubtDoubtIdRoute =
  AuthenticatedCommunityDoubtDoubtIdRouteImport.update({
    id: '/doubt/$doubtId',
    path: '/doubt/$doubtId',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedBattlePlaySessionIdRoute =
  AuthenticatedBattlePlaySessionIdRouteImport.update({
    id: '/play/$sessionId',
    path: '/play/$sessionId',
    getParentRoute: () => AuthenticatedBattleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/battle': typeof AuthenticatedBattleRouteWithChildren
  '/community': typeof AuthenticatedCommunityRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/mistakes': typeof AuthenticatedMistakesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/battle/history': typeof AuthenticatedBattleHistoryRoute
  '/battle/leaderboard': typeof AuthenticatedBattleLeaderboardRoute
  '/battle/mega': typeof AuthenticatedBattleMegaRoute
  '/battle/wallet': typeof AuthenticatedBattleWalletRoute
  '/community/doubts': typeof AuthenticatedCommunityDoubtsRoute
  '/community/feed': typeof AuthenticatedCommunityFeedRoute
  '/community/groups': typeof AuthenticatedCommunityGroupsRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/quiz/$sessionId': typeof AuthenticatedQuizSessionIdRoute
  '/results/$sessionId': typeof AuthenticatedResultsSessionIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/battle/': typeof AuthenticatedBattleIndexRoute
  '/community/': typeof AuthenticatedCommunityIndexRoute
  '/battle/play/$sessionId': typeof AuthenticatedBattlePlaySessionIdRoute
  '/community/doubt/$doubtId': typeof AuthenticatedCommunityDoubtDoubtIdRoute
  '/community/forum/$categoryId': typeof AuthenticatedCommunityForumCategoryIdRoute
  '/community/group/$groupId': typeof AuthenticatedCommunityGroupGroupIdRoute
  '/community/post/$postId': typeof AuthenticatedCommunityPostPostIdRoute
  '/api/public/hooks/mega-test-lifecycle': typeof ApiPublicHooksMegaTestLifecycleRoute
  '/api/public/hooks/process-withdrawals': typeof ApiPublicHooksProcessWithdrawalsRoute
  '/api/public/hooks/razorpay': typeof ApiPublicHooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/mistakes': typeof AuthenticatedMistakesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/battle/history': typeof AuthenticatedBattleHistoryRoute
  '/battle/leaderboard': typeof AuthenticatedBattleLeaderboardRoute
  '/battle/mega': typeof AuthenticatedBattleMegaRoute
  '/battle/wallet': typeof AuthenticatedBattleWalletRoute
  '/community/doubts': typeof AuthenticatedCommunityDoubtsRoute
  '/community/feed': typeof AuthenticatedCommunityFeedRoute
  '/community/groups': typeof AuthenticatedCommunityGroupsRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/quiz/$sessionId': typeof AuthenticatedQuizSessionIdRoute
  '/results/$sessionId': typeof AuthenticatedResultsSessionIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/battle': typeof AuthenticatedBattleIndexRoute
  '/community': typeof AuthenticatedCommunityIndexRoute
  '/battle/play/$sessionId': typeof AuthenticatedBattlePlaySessionIdRoute
  '/community/doubt/$doubtId': typeof AuthenticatedCommunityDoubtDoubtIdRoute
  '/community/forum/$categoryId': typeof AuthenticatedCommunityForumCategoryIdRoute
  '/community/group/$groupId': typeof AuthenticatedCommunityGroupGroupIdRoute
  '/community/post/$postId': typeof AuthenticatedCommunityPostPostIdRoute
  '/api/public/hooks/mega-test-lifecycle': typeof ApiPublicHooksMegaTestLifecycleRoute
  '/api/public/hooks/process-withdrawals': typeof ApiPublicHooksProcessWithdrawalsRoute
  '/api/public/hooks/razorpay': typeof ApiPublicHooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/battle': typeof AuthenticatedBattleRouteWithChildren
  '/_authenticated/community': typeof AuthenticatedCommunityRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/learning': typeof AuthenticatedLearningRoute
  '/_authenticated/mistakes': typeof AuthenticatedMistakesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/_authenticated/battle/history': typeof AuthenticatedBattleHistoryRoute
  '/_authenticated/battle/leaderboard': typeof AuthenticatedBattleLeaderboardRoute
  '/_authenticated/battle/mega': typeof AuthenticatedBattleMegaRoute
  '/_authenticated/battle/wallet': typeof AuthenticatedBattleWalletRoute
  '/_authenticated/community/doubts': typeof AuthenticatedCommunityDoubtsRoute
  '/_authenticated/community/feed': typeof AuthenticatedCommunityFeedRoute
  '/_authenticated/community/groups': typeof AuthenticatedCommunityGroupsRoute
  '/_authenticated/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/_authenticated/quiz/$sessionId': typeof AuthenticatedQuizSessionIdRoute
  '/_authenticated/results/$sessionId': typeof AuthenticatedResultsSessionIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/battle/': typeof AuthenticatedBattleIndexRoute
  '/_authenticated/community/': typeof AuthenticatedCommunityIndexRoute
  '/_authenticated/battle/play/$sessionId': typeof AuthenticatedBattlePlaySessionIdRoute
  '/_authenticated/community/doubt/$doubtId': typeof AuthenticatedCommunityDoubtDoubtIdRoute
  '/_authenticated/community/forum/$categoryId': typeof AuthenticatedCommunityForumCategoryIdRoute
  '/_authenticated/community/group/$groupId': typeof AuthenticatedCommunityGroupGroupIdRoute
  '/_authenticated/community/post/$postId': typeof AuthenticatedCommunityPostPostIdRoute
  '/api/public/hooks/mega-test-lifecycle': typeof ApiPublicHooksMegaTestLifecycleRoute
  '/api/public/hooks/process-withdrawals': typeof ApiPublicHooksProcessWithdrawalsRoute
  '/api/public/hooks/razorpay': typeof ApiPublicHooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/admin'
    | '/analytics'
    | '/battle'
    | '/community'
    | '/history'
    | '/home'
    | '/learning'
    | '/mistakes'
    | '/notifications'
    | '/pricing'
    | '/admin/moderation'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/battle/history'
    | '/battle/leaderboard'
    | '/battle/mega'
    | '/battle/wallet'
    | '/community/doubts'
    | '/community/feed'
    | '/community/groups'
    | '/profile/$userId'
    | '/quiz/$sessionId'
    | '/results/$sessionId'
    | '/admin/'
    | '/battle/'
    | '/community/'
    | '/battle/play/$sessionId'
    | '/community/doubt/$doubtId'
    | '/community/forum/$categoryId'
    | '/community/group/$groupId'
    | '/community/post/$postId'
    | '/api/public/hooks/mega-test-lifecycle'
    | '/api/public/hooks/process-withdrawals'
    | '/api/public/hooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/analytics'
    | '/history'
    | '/home'
    | '/learning'
    | '/mistakes'
    | '/notifications'
    | '/pricing'
    | '/admin/moderation'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/battle/history'
    | '/battle/leaderboard'
    | '/battle/mega'
    | '/battle/wallet'
    | '/community/doubts'
    | '/community/feed'
    | '/community/groups'
    | '/profile/$userId'
    | '/quiz/$sessionId'
    | '/results/$sessionId'
    | '/admin'
    | '/battle'
    | '/community'
    | '/battle/play/$sessionId'
    | '/community/doubt/$doubtId'
    | '/community/forum/$categoryId'
    | '/community/group/$groupId'
    | '/community/post/$postId'
    | '/api/public/hooks/mega-test-lifecycle'
    | '/api/public/hooks/process-withdrawals'
    | '/api/public/hooks/razorpay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/battle'
    | '/_authenticated/community'
    | '/_authenticated/history'
    | '/_authenticated/home'
    | '/_authenticated/learning'
    | '/_authenticated/mistakes'
    | '/_authenticated/notifications'
    | '/_authenticated/pricing'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/withdrawals'
    | '/_authenticated/battle/history'
    | '/_authenticated/battle/leaderboard'
    | '/_authenticated/battle/mega'
    | '/_authenticated/battle/wallet'
    | '/_authenticated/community/doubts'
    | '/_authenticated/community/feed'
    | '/_authenticated/community/groups'
    | '/_authenticated/profile/$userId'
    | '/_authenticated/quiz/$sessionId'
    | '/_authenticated/results/$sessionId'
    | '/_authenticated/admin/'
    | '/_authenticated/battle/'
    | '/_authenticated/community/'
    | '/_authenticated/battle/play/$sessionId'
    | '/_authenticated/community/doubt/$doubtId'
    | '/_authenticated/community/forum/$categoryId'
    | '/_authenticated/community/group/$groupId'
    | '/_authenticated/community/post/$postId'
    | '/api/public/hooks/mega-test-lifecycle'
    | '/api/public/hooks/process-withdrawals'
    | '/api/public/hooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  TermsRoute: typeof TermsRoute
  ApiPublicHooksMegaTestLifecycleRoute: typeof ApiPublicHooksMegaTestLifecycleRoute
  ApiPublicHooksProcessWithdrawalsRoute: typeof ApiPublicHooksProcessWithdrawalsRoute
  ApiPublicHooksRazorpayRoute: typeof ApiPublicHooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mistakes': {
      id: '/_authenticated/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof AuthenticatedMistakesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning': {
      id: '/_authenticated/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AuthenticatedLearningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/battle': {
      id: '/_authenticated/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof AuthenticatedBattleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community/': {
      id: '/_authenticated/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof AuthenticatedCommunityIndexRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/battle/': {
      id: '/_authenticated/battle/'
      path: '/'
      fullPath: '/battle/'
      preLoaderRoute: typeof AuthenticatedBattleIndexRouteImport
      parentRoute: typeof AuthenticatedBattleRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/results/$sessionId': {
      id: '/_authenticated/results/$sessionId'
      path: '/results/$sessionId'
      fullPath: '/results/$sessionId'
      preLoaderRoute: typeof AuthenticatedResultsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz/$sessionId': {
      id: '/_authenticated/quiz/$sessionId'
      path: '/quiz/$sessionId'
      fullPath: '/quiz/$sessionId'
      preLoaderRoute: typeof AuthenticatedQuizSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/$userId': {
      id: '/_authenticated/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthenticatedProfileUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community/groups': {
      id: '/_authenticated/community/groups'
      path: '/groups'
      fullPath: '/community/groups'
      preLoaderRoute: typeof AuthenticatedCommunityGroupsRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/community/feed': {
      id: '/_authenticated/community/feed'
      path: '/feed'
      fullPath: '/community/feed'
      preLoaderRoute: typeof AuthenticatedCommunityFeedRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/community/doubts': {
      id: '/_authenticated/community/doubts'
      path: '/doubts'
      fullPath: '/community/doubts'
      preLoaderRoute: typeof AuthenticatedCommunityDoubtsRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/battle/wallet': {
      id: '/_authenticated/battle/wallet'
      path: '/wallet'
      fullPath: '/battle/wallet'
      preLoaderRoute: typeof AuthenticatedBattleWalletRouteImport
      parentRoute: typeof AuthenticatedBattleRoute
    }
    '/_authenticated/battle/mega': {
      id: '/_authenticated/battle/mega'
      path: '/mega'
      fullPath: '/battle/mega'
      preLoaderRoute: typeof AuthenticatedBattleMegaRouteImport
      parentRoute: typeof AuthenticatedBattleRoute
    }
    '/_authenticated/battle/leaderboard': {
      id: '/_authenticated/battle/leaderboard'
      path: '/leaderboard'
      fullPath: '/battle/leaderboard'
      preLoaderRoute: typeof AuthenticatedBattleLeaderboardRouteImport
      parentRoute: typeof AuthenticatedBattleRoute
    }
    '/_authenticated/battle/history': {
      id: '/_authenticated/battle/history'
      path: '/history'
      fullPath: '/battle/history'
      preLoaderRoute: typeof AuthenticatedBattleHistoryRouteImport
      parentRoute: typeof AuthenticatedBattleRoute
    }
    '/_authenticated/admin/withdrawals': {
      id: '/_authenticated/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AuthenticatedAdminWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/razorpay': {
      id: '/api/public/hooks/razorpay'
      path: '/api/public/hooks/razorpay'
      fullPath: '/api/public/hooks/razorpay'
      preLoaderRoute: typeof ApiPublicHooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-withdrawals': {
      id: '/api/public/hooks/process-withdrawals'
      path: '/api/public/hooks/process-withdrawals'
      fullPath: '/api/public/hooks/process-withdrawals'
      preLoaderRoute: typeof ApiPublicHooksProcessWithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mega-test-lifecycle': {
      id: '/api/public/hooks/mega-test-lifecycle'
      path: '/api/public/hooks/mega-test-lifecycle'
      fullPath: '/api/public/hooks/mega-test-lifecycle'
      preLoaderRoute: typeof ApiPublicHooksMegaTestLifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/community/post/$postId': {
      id: '/_authenticated/community/post/$postId'
      path: '/post/$postId'
      fullPath: '/community/post/$postId'
      preLoaderRoute: typeof AuthenticatedCommunityPostPostIdRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/community/group/$groupId': {
      id: '/_authenticated/community/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/community/group/$groupId'
      preLoaderRoute: typeof AuthenticatedCommunityGroupGroupIdRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/community/forum/$categoryId': {
      id: '/_authenticated/community/forum/$categoryId'
      path: '/forum/$categoryId'
      fullPath: '/community/forum/$categoryId'
      preLoaderRoute: typeof AuthenticatedCommunityForumCategoryIdRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/community/doubt/$doubtId': {
      id: '/_authenticated/community/doubt/$doubtId'
      path: '/doubt/$doubtId'
      fullPath: '/community/doubt/$doubtId'
      preLoaderRoute: typeof AuthenticatedCommunityDoubtDoubtIdRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/battle/play/$sessionId': {
      id: '/_authenticated/battle/play/$sessionId'
      path: '/play/$sessionId'
      fullPath: '/battle/play/$sessionId'
      preLoaderRoute: typeof AuthenticatedBattlePlaySessionIdRouteImport
      parentRoute: typeof AuthenticatedBattleRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWithdrawalsRoute: typeof AuthenticatedAdminWithdrawalsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWithdrawalsRoute: AuthenticatedAdminWithdrawalsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedBattleRouteChildren {
  AuthenticatedBattleHistoryRoute: typeof AuthenticatedBattleHistoryRoute
  AuthenticatedBattleLeaderboardRoute: typeof AuthenticatedBattleLeaderboardRoute
  AuthenticatedBattleMegaRoute: typeof AuthenticatedBattleMegaRoute
  AuthenticatedBattleWalletRoute: typeof AuthenticatedBattleWalletRoute
  AuthenticatedBattleIndexRoute: typeof AuthenticatedBattleIndexRoute
  AuthenticatedBattlePlaySessionIdRoute: typeof AuthenticatedBattlePlaySessionIdRoute
}

const AuthenticatedBattleRouteChildren: AuthenticatedBattleRouteChildren = {
  AuthenticatedBattleHistoryRoute: AuthenticatedBattleHistoryRoute,
  AuthenticatedBattleLeaderboardRoute: AuthenticatedBattleLeaderboardRoute,
  AuthenticatedBattleMegaRoute: AuthenticatedBattleMegaRoute,
  AuthenticatedBattleWalletRoute: AuthenticatedBattleWalletRoute,
  AuthenticatedBattleIndexRoute: AuthenticatedBattleIndexRoute,
  AuthenticatedBattlePlaySessionIdRoute: AuthenticatedBattlePlaySessionIdRoute,
}

const AuthenticatedBattleRouteWithChildren =
  AuthenticatedBattleRoute._addFileChildren(AuthenticatedBattleRouteChildren)

interface AuthenticatedCommunityRouteChildren {
  AuthenticatedCommunityDoubtsRoute: typeof AuthenticatedCommunityDoubtsRoute
  AuthenticatedCommunityFeedRoute: typeof AuthenticatedCommunityFeedRoute
  AuthenticatedCommunityGroupsRoute: typeof AuthenticatedCommunityGroupsRoute
  AuthenticatedCommunityIndexRoute: typeof AuthenticatedCommunityIndexRoute
  AuthenticatedCommunityDoubtDoubtIdRoute: typeof AuthenticatedCommunityDoubtDoubtIdRoute
  AuthenticatedCommunityForumCategoryIdRoute: typeof AuthenticatedCommunityForumCategoryIdRoute
  AuthenticatedCommunityGroupGroupIdRoute: typeof AuthenticatedCommunityGroupGroupIdRoute
  AuthenticatedCommunityPostPostIdRoute: typeof AuthenticatedCommunityPostPostIdRoute
}

const AuthenticatedCommunityRouteChildren: AuthenticatedCommunityRouteChildren =
  {
    AuthenticatedCommunityDoubtsRoute: AuthenticatedCommunityDoubtsRoute,
    AuthenticatedCommunityFeedRoute: AuthenticatedCommunityFeedRoute,
    AuthenticatedCommunityGroupsRoute: AuthenticatedCommunityGroupsRoute,
    AuthenticatedCommunityIndexRoute: AuthenticatedCommunityIndexRoute,
    AuthenticatedCommunityDoubtDoubtIdRoute:
      AuthenticatedCommunityDoubtDoubtIdRoute,
    AuthenticatedCommunityForumCategoryIdRoute:
      AuthenticatedCommunityForumCategoryIdRoute,
    AuthenticatedCommunityGroupGroupIdRoute:
      AuthenticatedCommunityGroupGroupIdRoute,
    AuthenticatedCommunityPostPostIdRoute:
      AuthenticatedCommunityPostPostIdRoute,
  }

const AuthenticatedCommunityRouteWithChildren =
  AuthenticatedCommunityRoute._addFileChildren(
    AuthenticatedCommunityRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBattleRoute: typeof AuthenticatedBattleRouteWithChildren
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRouteWithChildren
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLearningRoute: typeof AuthenticatedLearningRoute
  AuthenticatedMistakesRoute: typeof AuthenticatedMistakesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedProfileUserIdRoute: typeof AuthenticatedProfileUserIdRoute
  AuthenticatedQuizSessionIdRoute: typeof AuthenticatedQuizSessionIdRoute
  AuthenticatedResultsSessionIdRoute: typeof AuthenticatedResultsSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBattleRoute: AuthenticatedBattleRouteWithChildren,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRouteWithChildren,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLearningRoute: AuthenticatedLearningRoute,
  AuthenticatedMistakesRoute: AuthenticatedMistakesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedProfileUserIdRoute: AuthenticatedProfileUserIdRoute,
  AuthenticatedQuizSessionIdRoute: AuthenticatedQuizSessionIdRoute,
  AuthenticatedResultsSessionIdRoute: AuthenticatedResultsSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  TermsRoute: TermsRoute,
  ApiPublicHooksMegaTestLifecycleRoute: ApiPublicHooksMegaTestLifecycleRoute,
  ApiPublicHooksProcessWithdrawalsRoute: ApiPublicHooksProcessWithdrawalsRoute,
  ApiPublicHooksRazorpayRoute: ApiPublicHooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
